### ISSUE TITLE
Add realmRoles to groups

### ISSUE THREAD

**Issue by Meecr0b** [CycriLabs/keycloak-configurator#90]
In our new setup we want to map realmRoles to groups. This in not implemented at the moment.

Example configuration:

```yaml
realms:
  dummy:
    realm-roles_foo:
      name: foo-realm-role
      containerID: dummy
    groups_bar:
      name: bar-group
      path: /bar-group
      realmRoles:
        - foo-realm-role
```

should result in

```yaml
dummy realm -> groups -> bar-group -> Role mapping -> foo-realm-role
```
