### ISSUE TITLE
Nested group import is not working

### ISSUE THREAD

**Issue by Meecr0b** [CycriLabs/keycloak-configurator#91]
I try to import the following nested group structe

```yaml
groups:
  foo:
    bar: {}
    baz: {}
```

with the following config:

```yaml
  realms:
    dummy:
      groups_0-foo:
        name: foo
        path: /foo
      groups_1-bar:
        name: bar
        path: /foo/bar
      groups_1-baz:
        name: baz
        path: /foo/baz
```

But this results in the following structure

![Image](https://github.com/user-attachments/assets/90a7d169-aa89-4264-8fdf-be4f49bc1699)

should we think about implementing the `subGroups` field into groups?
